language: php

php:
  - 7

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpcs lib --standard=psr2
